### tumx 0

echo '===================================================================='
echo ' groups 10 linear prob pre-trained epoch 100 asymm soft label'
CUDA_VISIBLE_DEVICES=1 python train_rnc.py --soft_label --asymm --groups 10 --epoch 100 --fine_tune --model_name '/home/rpu2/scratch/code/Rank-N-Contrast/save/AgeDB_models/RnC_AgeDB_resnet18_ep_400_lr_0.5_d_0.1_wd_0.0001_mmt_0.9_bsz_256_aug_crop,flip,color,grayscale_temp_2_label_l1_feature_l2_trial_0/ckpt_epoch_100.pth'
echo '===================================================================='
echo ' groups 10 linear prob pre-trained epoch 150 asymm soft label'
CUDA_VISIBLE_DEVICES=1 python train_rnc.py --soft_label --asymm --groups 10 --epoch 100 --fine_tune --model_name '/home/rpu2/scratch/code/Rank-N-Contrast/save/AgeDB_models/RnC_AgeDB_resnet18_ep_400_lr_0.5_d_0.1_wd_0.0001_mmt_0.9_bsz_256_aug_crop,flip,color,grayscale_temp_2_label_l1_feature_l2_trial_0/ckpt_epoch_150.pth'
echo '===================================================================='
echo ' groups 10 linear prob pre-trained epoch 200 asymm soft label'
CUDA_VISIBLE_DEVICES=1 python train_rnc.py --soft_label --asymm --groups 10 --epoch 100 --fine_tune --model_name '/home/rpu2/scratch/code/Rank-N-Contrast/save/AgeDB_models/RnC_AgeDB_resnet18_ep_400_lr_0.5_d_0.1_wd_0.0001_mmt_0.9_bsz_256_aug_crop,flip,color,grayscale_temp_2_label_l1_feature_l2_trial_0/ckpt_epoch_200.pth'
echo '===================================================================='
echo ' groups 20 linear prob pre-trained epoch 100 asymm soft label'
CUDA_VISIBLE_DEVICES=1 python train_rnc.py --soft_label --asymm --groups 20 --epoch 100 --fine_tune --model_name '/home/rpu2/scratch/code/Rank-N-Contrast/save/AgeDB_models/RnC_AgeDB_resnet18_ep_400_lr_0.5_d_0.1_wd_0.0001_mmt_0.9_bsz_256_aug_crop,flip,color,grayscale_temp_2_label_l1_feature_l2_trial_0/ckpt_epoch_100.pth'
echo '===================================================================='
echo ' groups 20 linear prob pre-trained epoch 150 asymm soft label'
CUDA_VISIBLE_DEVICES=1 python train_rnc.py --soft_label --asymm --groups 20 --epoch 100 --fine_tune --model_name '/home/rpu2/scratch/code/Rank-N-Contrast/save/AgeDB_models/RnC_AgeDB_resnet18_ep_400_lr_0.5_d_0.1_wd_0.0001_mmt_0.9_bsz_256_aug_crop,flip,color,grayscale_temp_2_label_l1_feature_l2_trial_0/ckpt_epoch_150.pth'
echo '===================================================================='
echo ' groups 20 linear prob pre-trained epoch 200 asymm soft label'
CUDA_VISIBLE_DEVICES=1 python train_rnc.py --soft_label --asymm --groups 20 --epoch 100 --fine_tune --model_name '/home/rpu2/scratch/code/Rank-N-Contrast/save/AgeDB_models/RnC_AgeDB_resnet18_ep_400_lr_0.5_d_0.1_wd_0.0001_mmt_0.9_bsz_256_aug_crop,flip,color,grayscale_temp_2_label_l1_feature_l2_trial_0/ckpt_epoch_200.pth'